### PR TITLE
Show also variables starting with underscores

### PR DESCRIPTION
**Pull request by jhrmnn**

### CODE REVIEW

**Comment by jhrmnn** [comment]
I just noticed that this version of the extension stops functioning for me at some point, whereas the version in nbextensions works, and I see they are different. Is the extension maintained in their tree?

**Comment by jfbercher** [comment]
I don't think that there is much difference, but indeed the last commits where done at `jupyter_contrib_nbextensions`. It would be better to commit at nbextensions, indeed, I will reply there... 
I am gonna to put a kind of deprecated warning here.

**Comment by jcb91** [comment]
I recently experimented with this using an adapted version of the namespace magics algorithm, to make the whole thing more succinct. I'll drop a PR on the contrib repo.

I do feel that the inclusion of underscored variables should be optional, though. I'm not sure how best to handle that though :thinking:

**Comment by jfbercher** [comment]
Yes, I agree that the inclusion of underscored variables should be optional, since it may clutter the listing (I remember having excluded some types for the same reason).

**Comment by jhrmnn** [comment]
Repo archived.

**Pull request closed without merging**
